### ISSUE TITLE
Is easyb still under development ?

### ISSUE THREAD

**Issue by beihaifeiwu** [easyb/easyb-core#11]

**Comment by rvowles** [comment]
not by me.

**Comment by beihaifeiwu** [comment]
Well, I have checket the maven central repository, found that there is no update since the version 0.99,
What happened?

**Comment by JuergenKindler** [comment]
beihaifeiwu, 
maybe the confusion comes from the fact that a rename has happened for some of the components. easyb-core was changed last August (some fixes I contributed related to before/after and reporting related to shared behaviours).

Cheers
  Jürgen

**Comment by beihaifeiwu** [comment]
Thanks for your answer, Jürgen
